// Runs once before the e2e suite: reset the test database schema and
// reseed fixtures so every run starts from the same known state.
import { execSync } from "child_process";
import path from "path";
import dotenv from "dotenv";

export default function globalSetup() {
  // Load env/test.env so prisma talks to the test db (port 5433).
  dotenv.config({ path: path.resolve(__dirname, "../../env/test.env") });

  const opts = { stdio: "inherit" as const, env: process.env };
  // Prisma 7 dropped `--skip-generate` from `db push`; the client is already
  // generated by the test container before this runs.
  execSync("npx prisma db push --force-reset", opts);
  execSync("npx tsx prisma/seed.ts", opts);
}
